### ISSUE TITLE
Not allow delete reminder

### ISSUE THREAD

**Issue by edgardmessias** [tomolimo/mask#1]
Open `front/reminder.form.php?id=1` and try delete reminder.

**Comment by tomolimo** [comment]
That's a known issue: the mask plugin cannot currently manage overlay dialog boxes.
I'm going to search a fix for this.

**Comment by tomolimo** [comment]
@edgardmessias please upgrade to latest release, it should fix the issue

**Comment by edgardmessias** [comment]
Great.
