### ISSUE TITLE
Issue between plugins (Mask and PDF)

### ISSUE THREAD

**Issue by LordBat** [tomolimo/mask#3]
Hi, 

i found an issue when i use a PDF plugin. When i try to get a pdf export like machine information or incident and i click on generate pdf, the pdf open in another tab but the mask plugin get stuck on the information and cant do nothing instead get back button, example on chrome, to return to the search form.

![image](https://cloud.githubusercontent.com/assets/19165739/23342108/2d18fa98-fc33-11e6-9b19-797f25c33d23.png)

Regards!

**Comment by tomolimo** [comment]
Hello,
Yes I confirm, this is a bug,
thank you for reporting,
regards,
Tomolimo

**Comment by roshanroche** [comment]
Dear @tomolimo any updates on this issue. 
Thanks

**Comment by tomolimo** [comment]
Sorry for being so late to answer to you, and to fix this issue.
Regards,
Tomolimo

**Comment by roshanroche** [comment]
Dear @tomolimo ,
i regret to inform you that the problem still persists.
when i upgrade the plugin it disables by default. but when i went to plugins and re enabled it problem is back.
and every time i login to glpi , plugin asks for upgrade

**Comment by LordBat** [comment]
That sounds like glpi issue and not a mask plugin issue.

The bug has been corrected, i tested and works.

**Comment by roshanroche** [comment]
Dear @LordBat ,
please check in ur plugin list , if Mask is Disabled or Upgrade,
for me also when i upgraded the Mask plug in it worked, but when i went to plug in list, Mask plugin was showing Upgrade, and when i clicked upgrade and enable i encounter the same problem.

**Comment by tomolimo** [comment]
Hello @roshanroche 

> i regret to inform you that the problem still persists.
> when i upgrade the plugin it disables by default. but when i went to plugins and re enabled it problem is back.
> and every time i login to glpi , plugin asks for upgrade

could you post on another issue, as the current issue is really fixed?

Thank you,
Tomolimo

**Comment by roshanroche** [comment]
Dear @tomolimo ,
see the following 
![image](https://user-images.githubusercontent.com/22425503/29365460-273f8654-82a8-11e7-9d29-faa071b9fe2e.png)
when this state , there is no screen haze.
as soon as i click on Upgrade and enable,
its back to the same issue of frozen screen.
please check in ur plugin list if Mask is enabled or disbaled.
with disabled state it works as expected.

**Comment by tomolimo** [comment]
Hello @roshanroche


could you post on another issue, as the current issue is really fixed?

Thank you,
Tomolimo
