### ISSUE TITLE
Mask Plugin issue with PDF plugin

### ISSUE THREAD

**Issue by roshanroche** [tomolimo/mask#4]
Dear @tomolimo ,
thank you for the update. i installed your fix on 2 glpi instances ,
and the problem seems to persist.
when i installed the new version it is disabled by default hence we feel the problem is fixed.
please check in ur plugin list . when mask plugin is Disabled or Upgrade the issue seems to be solved.
but as soon as u upgrade and enable it issue is back.
see the screen shot below.
![image](https://user-images.githubusercontent.com/22425503/29366096-17f65fc2-82aa-11e7-9713-22d89cd445a4.png)
this mode there is no frozen screen while printing pdf.
when plugin enabled issue persists.

**Comment by tomolimo** [comment]
Hello,
Which GLPI version?
Thank you

**Comment by roshanroche** [comment]
9.1.4 and 9.1.6
both same issue im facing

**Comment by tomolimo** [comment]
I must check as I made a test on 9.1.2

**Comment by roshanroche** [comment]
could you please check in your plugins list if Mask is enabled?
1st glance i also had this problem when i installed the updated plugin. it was not enabled.

**Comment by tomolimo** [comment]
The plugin has been working at our production site since March 2017 in version 2.1.4 on GLPI 9.1.2:
![image](https://user-images.githubusercontent.com/7569958/29367852-7eada10a-829e-11e7-85fb-7c190402bd73.png)

**Comment by roshanroche** [comment]
@tomolimo ,
Then must be an issue with glpi. Anyhow I will install glpi 9.1.2 tomorrow and will check and let u know.
Thanks again for ur work and support really appreciate it

**Comment by LordBat** [comment]
I think you need to check the logs or see on debug mode. i am testing on 9.1.4 and works.

![mask](https://user-images.githubusercontent.com/19165739/29368683-d4c96c2c-8276-11e7-865d-bc4a033bd773.PNG)

**Comment by tomolimo** [comment]
thank you @lordbat

**Comment by roshanroche** [comment]
Dear @tomolimo @LordBat 
guess what? the issue was browser cache :( i had to clear all browser history n cache.
working like a charm on chrome , firefox , 
ie still have issue even after clearing browser cache. will figure it out and update you.
issue was not with the plugin. im so sorry.
thanks for your efforts and support,appreciate it.

**Comment by roshanroche** [comment]
Dear @tomolimo ,
problem has been resolved. i confirm the issue was with browser cache , now works on IE also.
i will close this.
thanks for ur support again.
