### ISSUE TITLE
REQUEST - add message

### ISSUE THREAD

**Issue by benshoes** [tomolimo/mask#7]
Hello,
Thx a lot for this plgin.
Can you add a message at the center.
EX: waiting (in english)
Patienter (in french, for me :p)

**Comment by benshoes** [comment]
Can you insert a css for this plugin and not the base.css
It will be more simply if i we want to change color, opacity ...

**Comment by benshoes** [comment]
Hi,
One more thing.
If you don't fill all the request fields, you need to reload the page.
Can you add a condition.
Thx a lot for this awesome plugin

**Comment by tomolimo** [comment]
Hello @benshoes 

> Hi,
> One more thing.
> If you don't fill all the request fields, you need to reload the page.
> Can you add a condition.
> Thx a lot for this awesome plugin

Could you post into another issue this incident?
And describe how to reproduce it?

Please do not mix several questions/issues into the same post!

Thank you
Regards
Tomolimo
