### ISSUE TITLE
ISSUE - Request fields at ticket validation

### ISSUE THREAD

**Issue by benshoes** [tomolimo/mask#8]
GLPI: 9.5.4
Mask: 3.0.0
Hi,
If you don't fill all the request fields, you need to reload the page because the page is locked.
Can you add a condition.
![image](https://user-images.githubusercontent.com/53210764/112971057-225e9580-914f-11eb-8595-7a7bdbd29b5d.png)

Thx a lot for this awesome plugin

**Comment by tomolimo** [comment]
Hello @benshoes 
Could you post the versions of GLPI and plugin?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/mask/releases/tag/3.0.2

**Comment by benshoes** [comment]
Thx a lot
